config/routes.rb
Blogembed::Application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :blogs, only: [:index, :new, :create, :update, :destroy, :edit] do
      resources :posts
      resources :settings, only: [:edit, :update]
      resources :embeds, only: [:index, :show]
    end
  end

  get 'blog' => 'moonblog#index', as: 'moonblog'

  root 'welcome#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_one :setting

  validates :name, presence: true

  after_create :initialize_setting

private

  def initialize_setting
    setting = self.build_setting
    setting.save!
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_safe_resources

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = @user.blogs.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = @user.blogs.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = @user.blogs.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to user_blogs_path(current_user), notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to user_blogs_path(current_user), notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to user_blogs_url(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resources
      @user = User.find(params[:user_id])
      @blog = @user.blogs.where(id: params[:id], enable: true).first if @user
      @posts = @blog.posts.where(publish: true) if @blog
    end

    def set_safe_resources
      @user = current_user
      @blog = current_user.blogs.find(params[:id]) if @user && params[:id]
      @posts = @blog.posts if @blog
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :description, :enable)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def primary?(blog)
    blog.enable? ? "panel-info" : ""
  end
end

app/views/blogs/_form.html.erb
<%= form_for([current_user, @blog], html: { class: "form" }) do |f| %>
  <%= render partial: 'common/alert', locals: { resource: @blog } %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name (required)" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="checkbox">
    <%= f.label :enable %>
    <%= f.check_box :enable %>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/blogs/edit.html.erb
<h3 class="page-header">
  Edit Blog
  <span>
    <%= render partial: 'common/back_button', locals: { path: user_blogs_path(current_user) } %>
  </span>
</h3>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h3 class="page-header">
  Blogs
  <span>
    <%= link_to raw("<i class='icon-sitemap'></i> New Blog"), new_user_blog_path(current_user), class: 'btn btn-success btn-small' %>
  </span>
</h3>

<div class="row">
  <div class="col-lg-7">
    <% @blogs.each do |blog| %>
      <div class="panel <%= primary? blog %>">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= blog.name %>
            <span class="pull-right">
              <span class="label label-info"><%= blog.posts.size %> Posts</span>
              <span class="label label-info"><%= blog.enable? ? "Enabled" : "Disabled" %></span>
            </span>
          </h3>
        </div>

        <%= blog.description.present? ? blog.description : raw("<i class='text-muted'>No description</i>") %>

        <div class="panel-footer">
          <%= link_to raw("<i class='icon-file'></i> Post"), new_user_blog_post_url(current_user, blog), class: "btn btn-success btn-small" %>
          <%= link_to raw("<i class='icon-folder-open'></i> Manage"), user_blog_posts_url(current_user, blog), class: "btn btn-primary btn-small" %>
          <%= link_to raw("<i class='icon-gears'></i>"), edit_user_blog_setting_path(current_user, blog, blog.setting), class: "btn btn-default btn-small" %>

          <div class="pull-right">
            <%= link_to raw("<i class='icon-pencil'></i>"), edit_user_blog_path(current_user, blog), class: "btn btn-default btn-small" %>
            <%= link_to raw("<i class='icon-remove'></i>"), user_blog_path(current_user, blog), class: "btn btn-danger btn-small", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-5">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="icon-question-sign"></i> Info</h3>
      </div>
      <p>
        You can have multiple blogs, and embed each one wherever you wish.
      </p>
      <h4>Customizing</h4>
      <p>
        Embedded blogs do not show editing/administration buttons; they can be custom styled, check the <i class="icon-gears"></i> Settings section.
      </p>
      <h4>Embedding</h4>
      <p>
        Look for the <i class="icon-code"></i> icon when managing <i class='icon-folder-open'></i> a blog.
      </p>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h3 class="page-header">
  New blog
  <span>
    <%= render partial: 'common/back_button', locals: {path: user_blogs_path(current_user, @blog)}  %>
  </span>
</h3>

<%= render 'form' %>

app/views/blogs/show.html.erb
<% if @blog %>
  <h3 class="page-header">
    <%= @blog.name %>
    <% if is_allowed? params[:user_id] %>
      <span>
        <%= render partial: 'common/back_button', locals: { path: user_blogs_path(current_user) } %>
        <%= render partial: 'common/edit_button', locals: { path: edit_user_blog_path(current_user, @blog) } %>
      </span>
    <% end %>
  </h3>

  <% if @post %>
    <% @posts.each do |post| %>
      <p>LIST POSTS HERE</p>
    <% end %>
  <% else %>
    <p class="alert">This blog has no posts...</p>
  <% end %>
<% else %>
  <h3 class="page-header">Sorry...</h3>
  <p class="alert">This blog is not available.</p>
<% end %>