config/routes.rb
Blogembed::Application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :blogs, only: [:index, :new, :create, :update, :destroy, :edit] do
      resources :posts
      resources :settings, only: [:edit, :update]
      resources :embeds, only: [:index, :show]
    end
  end

  get 'blog' => 'moonblog#index', as: 'moonblog'

  root 'welcome#index'
end

app/controllers/embeds_controller.rb
class EmbedsController < ApplicationController
  layout 'embed'

  before_action :set_resources

  def index
    @resources = @posts
  end

  def show
    @resource = @posts.find(params[:id])
  end

private

  def set_resources
    @user = User.find(params[:user_id])
    @blog = @user.blogs.where(id: params[:blog_id], enable: true).first if @user
    @posts = @blog.posts.where(publish: true).order('created_at DESC') if @blog
    @setting = @blog.setting if @blog
  end
end

app/views/embeds/_post.html.erb
<% shorten ||= nil %><%# stupid rails, undefined local variable, mumble mumble... %>

<h2 class="blog-title">
  <%= link_to_unless_current post.title, user_blog_embed_url(params[:user_id], @blog.id, post.to_param) %>
</h2>

<%= render partial: 'common/post_body', locals: { post: post, shorten: shorten } %>

app/views/embeds/index.html.erb
<% if @blog %>
  <div class="row">
    <div class="col-sm-8">
      <% if @resources.present? %>
        <% @resources.each do |post| %>
          <%= render(partial: 'embeds/post', locals: { post: post, shorten: true }) %>
          <hr>
        <% end %>
      <% else %>
        <h3>:( A lonely blog... on a lonely journey...</h3>
      <% end %>
    </div>

    <% if @resources.any? %>
      <div class="col-sm-4">
        <%= render partial: 'posts/archive', locals: { posts: @resources } %>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class="page-header">Sorry...</h3>
  <p class="alert">This blog is not available.</p>
<% end %>

app/views/embeds/show.html.erb
<%= render partial: 'post', locals: { post: @resource } %>