config/routes.rb
Blogembed::Application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :blogs, only: [:index, :new, :create, :update, :destroy, :edit] do
      resources :posts
      resources :settings, only: [:edit, :update]
      resources :embeds, only: [:index, :show]
    end
  end

  get 'blog' => 'moonblog#index', as: 'moonblog'

  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog

  def to_param
    "#{self.id}-#{self.created_at.strftime("%Y-%m-%d").parameterize}-#{self.title.parameterize}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_action :set_resources, only: [:show, :index]
  before_action :set_safe_resources, only: [:edit, :update, :create, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    redirect_to(root_path) and return unless @blog.present?
    @post = @blog.posts.new

    if is_allowed? params[:user_id]
      @posts = @blog.posts.order('created_at DESC')
    else
      @posts = @blog.posts.where(publish: true).order('created_at DESC')
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @blog = current_user.blogs.find(params[:blog_id])
    @post = @blog.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @blog.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [current_user, @blog, @post], notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [current_user, @blog, @post], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_blog_posts_url(current_user, @blog) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resources
      if is_allowed? params[:user_id]
        @user = current_user
        @blog = @user.blogs.find(params[:blog_id])
        @post = @blog.posts.find(params[:id]) if @blog && params[:id].present?
      else
        @user = User.find(params[:user_id])
        @blog = @user.blogs.where(id: params[:blog_id], enable: true).first
        @post = @blog.posts.where(id: params[:id], publish: true).first if @blog && params[:id].present?
      end
    end

    def set_safe_resources
      @blog = current_user.blogs.where(id: params[:blog_id]).first
      @post = @blog.posts.find(params[:id]) if @blog && params[:id].present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :publish)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  def shorten?(shorten=nil)
    true if shorten == true
  end

  def disqus_shortname(post)
    post.blog.setting.disqus_shortname
  end

  def display_comments?(user_id, post)
    if action_name == 'show' && disqus_shortname(post).present?
      true
    else
      false
    end
  end

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/views/posts/_archive.html.erb
<div class="panel">
  <div class="panel-heading">
    <h3 class="panel-title">Archive</h3>
  </div>
  <ul class="list-unstyled">
    <% posts.chunk { |post| post.created_at.strftime("%Y") }.each do |year, posts| %>
      <li>
        <%= year %>
        <ul style="list-style:none;padding-left:10px;">
          <% posts.chunk { |post| post.created_at.strftime("%B") }.each do |month, posts| %>
            <li>
              <%= month %>
              <ul style="list-style:none;padding-left:10px;">
                <% posts.each do |post| %>
                  <li>
                    <%= link_to_unless_current post.title, path_to_post_for_controller(controller_name, user.id, @blog.id, post.to_param) %>
                    <small class="text-muted"><em><%= post.created_at.strftime('%b %e') %></em></small>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/_form.html.erb
<%= form_for([current_user, @blog, @post]) do |f| %>
  <%= render partial: 'common/alert', locals: { resource: @post } %>

  <div class="form-group">
    <div class="row">
      <div class="col-lg-6">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>
      <div class="col-lg-6">
        <%= f.text_field :author, placeholder: "Author", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.text_area :body, placeholder: "Body", class: "form-control", rows: "20" %>
  </div>

  <div class="checkbox">
    <%= f.label :publish %>
    <%= f.check_box :publish %>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% shorten ||= nil %>

<h2 class="blog-title">
  <%= link_to_unless_current post.title, user_blog_post_path(params[:user_id], @blog.id, post.to_param) %>
  <% if user_signed_in? && controller_name != 'embeds' %>
    <span>
      <%= render(partial: 'common/show_button', locals: { path: user_blog_post_path(current_user, @blog, post.to_param) }) unless current_page? user_blog_post_path(current_user, @blog, post.to_param) %>
      <%= render(partial: 'common/edit_button', locals: { path: edit_user_blog_post_path(current_user, @blog, post.to_param) }) %>
      <%= render(partial: 'common/destroy_button', locals: { path: user_blog_post_path(current_user, @blog, post.to_param) }) %>
    </span>
  <% end %>
</h2>

<%= render partial: 'common/post_body', locals: { post: post, shorten: shorten } %>

app/views/posts/edit.html.erb
<h3 class="page-header">
  Edit Blog Post – <%= @post.blog.name %>
  <span>
    <%= render partial: 'common/back_button', locals: { path: user_blog_posts_path(current_user, @blog) } %>
    <%= render partial: 'common/show_button', locals: { path: user_blog_post_path(current_user, @blog, @post) } %>
  </span>
</h3>

<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/index.html.erb
<h3 class="page-header">
  <%= @blog.name %>
  <% if user_signed_in? && is_allowed?(params[:user_id]) %>
    <span>
      <%= render partial: 'common/back_button', locals: { path: user_blogs_path(current_user) } %>
      <%= link_to raw('<i class="icon-file"></i> Post'), new_user_blog_post_path(current_user.id, params[:blog_id]), class: "btn btn-success btn-small" %>
      <a data-toggle="modal" href="#embed-code" class="btn btn-primary btn-small"><i class="icon-code"></i></a>
    </span>
  <% end %>
</h3>

<div class="row">

  <div class="col-lg-8">
    <% if @posts.present? %>
      <% @posts.each do |post| %>
        <%= render(partial: 'post', object: post, locals: { shorten: true }) %>
        <hr>
      <% end %>
    <% else %>
      <% if is_allowed? params[:user_id] %>
        <%= render "form" %>
      <% else %>
        <p class="alert">No posts here...</p>
      <% end %>
    <% end %>
  </div>

  <div class="col-lg-4">
    <% if @posts.any? %>
      <%= render partial: 'archive', locals: { posts: @posts } %>
    <% elsif is_allowed?(params[:user_id]) %>
      <div class="panel">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="icon-question-sign"></i> Info</h3>
        </div>
        <p>
          You don't seem to have any blog posts!
          Why not write your first one now? <br>Go on, don't be shy!
        </p>
      </div>
    <% else %>
      <div class="panel">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="icon-question-sign"></i> Info</h3>
        </div>
        <p>
          Publishing is good for your health :) <a href="/">get your own blog</a> and start writing!
        </p>
      </div>
    <% end %>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="embed-code">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Embed Snippet</h4>
      </div>
      <div class="modal-body">
        <p>
          To embed your blog on your site, copy and paste the code bellow into your web page HTML.
        </p>

        <pre>
<%= "<iframe style='border:none;width:100%;height:800px;' src='#{user_blog_embeds_url(current_user, @blog)}/' seamless sandbox='allow-same-origin allow-scripts allow-forms'></iframe>" %>
        </pre>

        </pre>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/posts/new.html.erb
<h3 class="page-header">
  Post – <%= @post.blog.name %>
  <span><%= render partial: 'common/back_button', locals: { path: user_blog_posts_path(current_user, @blog) } %></span>
</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if user_signed_in? %>
  <h3 class="page-header">
    Preview – <%= @post.blog.name %>
    <span>
      <%= render partial: 'common/back_button', locals: { path: user_blog_posts_path(current_user, @blog) } %>
    </span>
  </h3>
<% end %>

<%= render partial: 'post', object: @post %>