config/routes.rb
Blogembed::Application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :blogs, only: [:index, :new, :create, :update, :destroy, :edit] do
      resources :posts
      resources :settings, only: [:edit, :update]
      resources :embeds, only: [:index, :show]
    end
  end

  get 'blog' => 'moonblog#index', as: 'moonblog'

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MoonBlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= favicon_link_tag 'favicon-invert.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <link rel="stylesheet" href="http://yandex.st/highlightjs/7.3/styles/xcode.min.css">
  <script src="http://yandex.st/highlightjs/7.3/highlight.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= gflash %>
<%= js add_gritter(flash[:error], title: "Error") if flash[:error] %>
<%= js add_gritter(flash[:notice], title: "Notice") if flash[:notice] %>
<%= js add_gritter(flash[:alert], title: "Alert") if flash[:alert] %>

<div class="container">

  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <!-- .navbar-toggle is used as the toggle for collapsed navbar content -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="navbar-brand <%= active "/" %>" href="/"><i class="icon-moon glow"></i></a>
    </div>

    <!-- Place everything within .nav-collapse to hide it until above 768px -->
    <div class="nav-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="<%= active user_blogs_path(current_user) %>"><a href="<%= user_blogs_path(current_user) %>" title="Dashboard"><i class="icon-dashboard"></i> <span class="hidden-phone">Dashboard</span></a></li>
          <li class="<%= active destroy_user_session_path %>"><%= link_to raw("<i class='icon-lock'></i> <span class='hidden-phone'>Logout</span> <span class='badge'>#{current_user.email}</span></a>"), destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li class="<%= active new_user_registration_path %>"><a href="<%= new_user_registration_path %>"><i class="icon-key"></i> Register</a></li>
          <li class="<%= active user_session_path %>"><a href="<%= user_session_path %>"><i class="icon-unlock"></i> Login</a></li>
        <% end %>
      </ul>
    </div>

  </nav>

  <div class="row">
    <div class="col-lg-12">

      <%= yield %>

      <hr>

      <footer>
        <small>
          <a href="mailto:moonblog@specificidea.com?subject=feedback" "email me"><i class="icon-envelope"></i> Questions?</a> • <%= link_to "Our Blog", moonblog_path %>
        </small>
      </footer>
      <br>
    </div>
  </div>

</div>

</body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>MoonBlog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>

  <style type="text/css" media="screen">
    body {
      background-color: transparent;
      padding:0;
      margin:0;
    }
    body .container {
      padding:0;
      margin:0;

      max-width: 100%;
      overflow-x: hidden;
    }
  </style>

  <style type="text/css" media="screen">
    <%= sanitize_css(@setting.custom_css) if @setting %>
  </style>

  <link href='http://fonts.googleapis.com/css?family=Fanwood+Text:400,400italic' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="http://yandex.st/highlightjs/7.3/styles/xcode.min.css">
  <script src="http://yandex.st/highlightjs/7.3/highlight.min.js"></script>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-12">
      <% if @blog %>
        <h3 class="page-header">
          <%= @blog.name || "Blog" %>
        </h3>

        <%= yield %>
      <% else %>
        <p>No blog found here...</p>
      <% end %>
    </div>
  </div>
</div>

<script>
  (function(){
    // trigger load event for parent of iframe
    parent.$('body').trigger('moonblog:load');

    // also trigger when everything is loaded, again
    window.onload = function() {
      parent.$('body').trigger('moonblog:load');
    }
  })(window,document,$);

  jQuery(document).on("ready page:change", function() {
    $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
  });
</script>

</body>
</html>